### ISSUE TITLE
Compositions currently ignore concentrations

### ISSUE THREAD

**Issue by RasmusRendal** [RasmusRendal/chemilang#15]
Expected behaviour:

When I compile the `.chem` file 
```
module something {
    input: x;
    output: y;
    private: z;
    concentrations: {
        z := 50;
    }
}
module main {

    compositions: 
        x = something(y);
}
```
Then the initial concentration of main_something_z should be 50. 

Actual behaviour:
The `Module::ApplyCompositions` function has no code to check for concentrations in submodules, and will instead ignore them

**Comment by adramaxxx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Simon Berg](https://trello.com/c/rFj2Y4QJ/79-simon-berg)
