### ISSUE TITLE
Use structs in the module code instead of typedefs for the tuples

### ISSUE THREAD

**Issue by RasmusRendal** [RasmusRendal/chemilang#16]
This should make the code much more readable. 

For example, the current typedef for `composition`s. If we used a struct that looked like this instead:
```cpp
struct composition {
    Module *module;
    speciesMapping inputMapping;
    speciesMapping outputMapping;
};
```
Then accessing a member would be the syntax `composition.inputMapping`, instead of `std::get<1>(composition)`.

**Comment by adramaxxx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Anders](https://trello.com/c/w4aEyuCx/77-anders)
