### ISSUE TITLE
Ban braceless else statements

### ISSUE THREAD

**Issue by RasmusRendal** [RasmusRendal/chemilang#19]
The code
```cpp
if (condition) {
    doSomething();
    doSomethingElse();
} else
    function()
anotherFunction()
```
Is valid, but it looks awful. We need some sort of CI check to stop it.

**Comment by adramaxxx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Anders](https://trello.com/c/w4aEyuCx/77-anders)

**Comment by Andrikz** [comment]
This is not possible in clang-format
