### ISSUE TITLE
Throw error on unrecognized command-line argument

### ISSUE THREAD

**Issue by RasmusRendal** [RasmusRendal/chemilang#21]
Currently, it just skips arguments not matched in the if-else block. The expected behaviour should be that `chemilang -O -Y example.chem` should throw an error.

**Comment by adramaxxx** [comment]
maybe we should also add the -h functionality as in crnsimul

**Comment by adramaxxx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Anders](https://trello.com/c/w4aEyuCx/77-anders)
