### ISSUE TITLE
Include statement

### ISSUE THREAD

**Issue by RasmusRendal** [RasmusRendal/chemilang#56]
With our new fancy [clock](https://github.com/RasmusRendal/crnsimul/blob/milestone/1.0/examples/oscillator.crn), it would make sense to package that as part of a standard library. Then we could put all of the basic mathematical operations there as well.

I'm imagining a statement such as `import clock.chem`, which searches multiple directories, in the following order:
 1. `./clock.chem`
 2. `./chemlib/clock.chem`
 3. `/usr/share/chemilang/chemlib/clock.chem`

We'd have a folder in the repository called `chemlib`, which then contains our standard library.

**Comment by ghost** [comment]
Maybe have prefix name for Chemlig such as `import chemlib/clock.chem` So that the user still can have a clock.chem file

**Comment by RasmusRendal** [comment]
The idea behind having the order was that if the user had a `./clock.chem` file, it would be loaded instead of the one in the standard lib.
