### ISSUE TITLE
Concentrations in reactions are being increased at the beginning of the line for some reason

### ISSUE THREAD

**Issue by RasmusRendal** [RasmusRendal/chemilang#67]
Tried to compile the GOL example, and there are numbers at the beginning of the line that shouldn't be there. Attached is the chemilang code, with a txt file ending to make GitHub happy. 
[gol.txt](https://github.com/RasmusRendal/chemilang/files/4563092/gol.txt)

Theory: Composition number prepending gets applied in such a way that chemicals are actually named 2Specie, which results in them being interpreted as two of the specie Specie, instead of a specific name.

**Comment by RasmusRendal** [comment]
Seems that #73 really fixed this.

**Comment by adramaxxx** [comment]
pogchamp
